INSERT INTO article (title, content) VALUES ("title1", "content");
INSERT INTO article (title, content) VALUES ("title2", "content");
INSERT INTO article (title, content) VALUES ("title3", "content");
INSERT INTO article (title, content) VALUES ("title4", "content");
INSERT INTO article (title, content) VALUES ("title5", "content");
INSERT INTO article (title, content) VALUES ("title6", "content");
INSERT INTO article (title, content) VALUES ("title7", "content");
INSERT INTO article (title, content) VALUES ("title8", "content");
INSERT INTO article (title, content) VALUES ("title9", "content");
INSERT INTO article (title, content) VALUES ("title10", "content");
INSERT INTO article (title, content) VALUES ("title11", "content");
INSERT INTO article (title, content) VALUES ("title12", "content");
INSERT INTO article (title, content) VALUES ("title13", "content");
INSERT INTO article (title, content) VALUES ("title14", "content");
INSERT INTO article (title, content) VALUES ("title15", "content");
INSERT INTO article (title, content) VALUES ("title16", "content");
INSERT INTO article (title, content) VALUES ("title17", "content");
INSERT INTO article (title, content) VALUES ("title18", "content");
INSERT INTO article (title, content) VALUES ("title19", "content");
INSERT INTO article (title, content) VALUES ("title20", "content");
INSERT INTO article (title, content) VALUES ("title21", "content");
INSERT INTO article (title, content) VALUES ("title22", "content");
INSERT INTO article (title, content) VALUES ("title23", "content");
INSERT INTO article (title, content) VALUES ("title24", "content");
INSERT INTO category (category_name) VAlUES ("spring");
INSERT INTO category (category_name, parent_id) VALUES("boot", 1);
INSERT INTO category (category_name, parent_id) VALUES("legacy", 1);
INSERT INTO category (category_name) VAlUES ("mysql");
INSERT INTO category (category_name) VAlUES ("javascript");